# Generated by Django 3.2.6 on 2021-08-28 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Memasik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_image', models.ImageField(max_length=255, null=True, upload_to='download/')),
                ('tags', models.CharField(max_length=255)),
                ('date_mem', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='MemIntermediate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_image', models.ImageField(max_length=255, null=True, upload_to='download/')),
            ],
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_roles', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_tag', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=255)),
                ('user_password', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('date', models.DateField()),
                ('id_name_role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='MemApps.roles')),
            ],
        ),
        migrations.CreateModel(
            name='MyGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_mem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MemApps.memasik')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MemApps.users')),
            ],
        ),
        migrations.CreateModel(
            name='MemTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_mem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MemApps.memasik')),
                ('id_tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MemApps.tags')),
            ],
        ),
        migrations.CreateModel(
            name='Massege',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('massege', models.TextField()),
                ('date_time_massege', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MemApps.users')),
            ],
        ),
    ]
