# Generated by Django 3.2.6 on 2021-09-13 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MemApps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='memintermediate',
            name='id_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MemApps.users'),
        ),
    ]
