# Generated by Django 3.2.6 on 2021-09-30 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MemApps', '0002_memintermediate_id_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MemTags',
        ),
    ]
